name="c"
display_name="C"
latest_ver="0.0.0"
License="GPLv3"

[lang.Installer]
Notes="This programming language came fromw https://winlibs.com/ which do not contain following this LLVM/Clang/LLD/LLDB | beside that this pl(programming language) use ucrt and cli doesnt support @msvcrt/ucrt to tell the different"
#Types="archives"/"msi"/"nsis"/etc..

[lang.0_0_0]
version="16.2.0"
url="https://github.com/brechtsanders/winlibs_mingw/releases/download/16.2.0posix-14.0.0-ucrt-r1/winlibs-x86_64-posix-seh-gcc-16.2.0-mingw-w64ucrt-14.0.0-r1.7z"
#hash=""
#hash_url=""
#minisig=""
#minisig_url=""
#sig=""
#sig_url=""