name="lang"
display_name="lang"
latest_ver="3.02"
License=""

#[lang.Installer]
#Notes=""
#Types="archives"/"msi"/"nsis"/etc..

[lang.3_02]
version="3.02"
url="https://www.nasm.us/pub/nasm/releasebuilds/3.02/win64/nasm-3.02-win64.zip"
hash="sha256:161D0BFAFF53C2F9E9F3E69FD0672323EBABAFD1268976A5CEC11BE92A19AEE7"
#hash_url=""
#minisig=""
#minisig_url=""
#sig=""
#sig_url=""