name="V"
display_name="vlang"
latest_ver="0.5.2"
License="MIT"

[lang.Installer]
ReqAdmin=false
path="%localappdata%/vlang"

[lang.0_5_2]
version="0.5.2"
url="https://github.com/vlang/v/releases/download/0.5.2/v_windows.zip"
hash="sha256:5f1d619b6b04a2b54b4ad21826a25bdcba2acf75a941c8f72fc95672b6b064ca"
#hash_url=""
#minisig=""
#minisig_url=""

[lang.0_5_1]
version="0.5.1"
url="https://github.com/vlang/v/releases/download/0.5.1/v_windows.zip"
hash="sha256:705bda7f87ccf1fbd24657a3d5767196c44a3d963ff647d7ca6d9beace2b619f"