name="zig"
latest_ver="0.17.0"

[lang.Installer]
ReqAdmin=false
path="%localappdata%/zig" # interpert to ablosute path

[langs.0_17_0]
version="0.17.0"
url="https://ziglang.org/builds/zig-x86_64-windows-0.17.0-dev.2251+1175a3e99.zip"
minisig_url="https://ziglang.org/builds/zig-x86_64-windows-0.17.0-dev.2251+1175a3e99.zip.minisig"

[langs.0_16_0]
version="0.16.0"
url="https://ziglang.org/download/0.16.0/zig-x86_64-windows-0.16.0.zip"
minisig_url="https://ziglang.org/download/0.16.0/zig-x86_64-windows-0.16.0.zip.minisig"